#!/bin/bash
echo "Broadcast:"
ifconfig | awk '/broadcast/{print $6}'
ping -o 192.168.23.255 &> /dev/null
echo "All IP adresses which are part of the same subnet:"
arp -a | awk '/192.168./{gsub(/[()]/,""); print $2}'
